
[[rule]]
toolName = "glob"
decision = "allow"
priority = 50

[[rule]]
toolName = "search_file_content"
decision = "allow"
priority = 50

[[rule]]
toolName = "list_directory"
decision = "allow"
priority = 50

[[rule]]
toolName = "read_file"
decision = "allow"
priority = 50

[[rule]]
toolName = "read_many_files"
decision = "allow"
priority = 50

[[rule]]
toolName = "google_web_search"
decision = "allow"
priority = 50
