name: 'Approved Fork Execution'

on:
  pull_request_target:

jobs:
  check-fork:
    name: 'Check if PR is from a fork'
    runs-on: 'ubuntu-latest'
    outputs:
      is-fork: ${{ steps.check_fork.outputs.is-fork }}
    steps:
      - id: check_fork
        run: echo "is-fork=${{ github.event.pull_request.head.repo.fork }}" >> $GITHUB_OUTPUT

  run-tests:
    name: 'Run Tests'
    needs: check-fork
    runs-on: 'ubuntu-latest'

    # For PRs from forks, require approval via an environment.
    # For internal PRs (from the same repo), run without approval.
    environment:
      name: ${{ needs.check-fork.outputs.is-fork == 'true' && 'e2e-on-fork' || '' }}

    steps:
      # We must checkout the specific PR head SHA because this workflow runs in the context
      # of the base branch, not the PR merge commit.
      - name: 'Checkout PR code'
        uses: 'actions/checkout@v4'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'

      - name: 'Run test with secret'
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
        run: |
          echo "This step demonstrates using a secret."
          if [ -n "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY is available."
          else
            echo "GEMINI_API_KEY is not available."
            exit 1
          fi
