name: 'Eval'

on:
  workflow_dispatch:
    
defaults:
  run:
    shell: 'bash'

jobs:
  eval:
    name: 'Eval'
    if: >-
      github.repository == 'google-gemini/gemini-cli'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5

      - name: 'Set up Node.js 24.x'
        uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020' # ratchet:actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: 'Set up Python'
        uses: 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065' # ratchet:actions/gsetup-python@v5
        with:
          python-version: '3.12'

      - name: 'Install and configure Poetry'
        uses: 'snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a' # ratchet:snok/install-poetry@v1
      
      - name: 'Clone evaluation harness'
        env:
          EVAL_GH_TOKEN: '${{ secrets.EVAL_GH_TOKEN }}'
          EVAL_GH_REPO: '${{ vars.EVAL_GH_REPO }}'
        run: git clone "https://x-access-token:${EVAL_GH_TOKEN}@github.com/${EVAL_GH_REPO}"

      - name: 'Download evaluation data'
        working-directory: ./agent-prototypes
        run: ./download_swebench_data.sh  
      
      - name: 'Install evaluation harness'
        working-directory: ./agent-prototypes
        run: poetry install
  
      - name: 'Authenticate with Google'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  
      - name: 'Run evaluation harness'
        working-directory: ./agent-prototypes
        env:
          GITHUB_TOKEN: '${{ secrets.EVAL_GH_TOKEN }}'
          DEFAULT_VERTEXAI_PROJECT: '${{ secrets.EVAL_VERTEXAI_PROJECT }}'
          GEMINI_API_KEY: '${{ secrets.EVAL_GEMINI_API_KEY }}'
          GCLI_LOCAL_FILE_TELEMETRY: True
        run: poetry run exp_run --experiment-config-name gcli_2.5_pro