name: 'Eval'

on:
  workflow_dispatch:
    
defaults:
  run:
    shell: 'bash'

jobs:
  eval:
    if: |-
      github.repository == 'google-gemini/gemini-cli'
    name: 'Eval'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Set up Node.js 24.x'
        uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020' # ratchet:actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: 'Set up Python'
        uses: 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065' # ratchet:actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install and configure Poetry'
        uses: 'snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a' # ratchet:snok/install-poetry@v1
      
      - name: 'Clone evaluation harness'
        env:
          GITHUB_TOKEN: '${{ secrets.EVAL_GH_TOKEN }}'
          GITHUB_REPOSITORY: '${{ vars.EVAL_GH_REPO }}'
        run: git clone $EVAL_GH_REP0

      - name: 'Download evaluation data'
        working-directory: ./agent-prototypes
        run: ./download_swebench_data.sh  
      
      - name: 'Install evaluation harness'
        working-directory: ./agent-prototypes
        run: poetry install
      
      - name: 'Run evaluation harness'
        working-directory: ./agent-prototypes
        env:
          GITHUB_TOKEN: '${{ secrets.EVAL_GH_TOKEN }}'
          DEFAULT_VERTEXAI_PROJECT: '${{ secrets.EVAL_VERTEXAI_PROJECT }}'
          GEMINI_API_KEY: '${{ secrets.EVAL_GEMINI_API_KEY }}}'
          GCLI_LOCAL_FILE_TELEMETRY: True
        run: poetry run exp_run --experiment-config-name gcli_2.5_pro
