# .github/workflows/pr-checks.yml
name: 'Checks'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'
  merge_group:

permissions:
  contents: 'read'
  packages: 'write'
  pull-requests: 'write'
  security-events: 'write'
  checks: 'write'
  statuses: 'write'
  actions: 'read'
  attestations: 'read'
  deployments: 'read'
  discussions: 'read'
  issues: 'read'
  pages: 'read'
  repository-projects: 'read'
  id-token: 'write'

jobs:
  build-and-publish:
    name: 'Build and Publish CI Bundle'
    uses: './.github/workflows/build-and-publish.yml'

  ci:
    name: 'CI Checks'
    needs: 'build-and-publish'
    uses: './.github/workflows/ci.yml'
    with:
      version: '${{ needs.build-and-publish.outputs.version }}'

  e2e:
    name: 'E2E Checks'
    needs: 'build-and-publish'
    uses: './.github/workflows/e2e.yml'
    with:
      version: '${{ needs.build-and-publish.outputs.version }}'
