name: 'Trigger E2E'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'
  workflow_dispatch:
    inputs:
      branch_ref:
    steps:
      - name: 'Save Repo name'
        env:
          # Replace with github.event.pull_request.base.repo.full_name when switched to listen on pull request events. This repo name does not contain the org which is needed for checkout.
          REPO_NAME: '${{ github.event.repository.name }}'
          REPO_NAME: '${{ github.event.pull_request.head.repo.full_name || github.repository }}'
        run: |
          mkdir -p ./pr
          echo '${{ env.REPO_NAME }}' > ./pr/repo_name
          path: 'pr/'
  trigger_e2e:
    name: 'Trigger e2e'
    runs-on: 'gemini-cli-ubuntu-16-core'
    steps:
      - id: 'trigger-e2e'
        run: |
          echo "Trigger e2e workflow"
